
EVAL  [0]
Traceback (most recent call last):
  File "main.py", line 73, in <module>
    optimizer = badam(model, mean_eta=badam_etas[exp], std_init=badam_stds[exp])
KeyError: 'cartpole'
Traceback (most recent call last):
  File "main.py", line 73, in <module>
    optimizer = badam(model, mean_eta=badam_etas[exp], std_init=badam_stds[exp])
KeyError: 'cartpole'